import gymnasium as gym
from gymnasium import spaces
import numpy as np

from physics import RocketPhysics
from renderer import RocketRenderer

class RocketEnv(gym.Env):

    def __init__(self, render_mode=None):
        super().__init__()
        self.physics = RocketPhysics()
        self.renderer = RocketRenderer(render_mode=render_mode) if render_mode else None

        self.action_space = spaces.Discrete(6)
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(6,),
            dtype=np.float32
        )
        self.steps = 0
        self.episode_count = 0
        self.prev_shaping = None
        
    def get_observation(self):
        return np.array([
            self.physics.pos[0] / 10.0,
            self.physics.pos[1] / 20.0,
            self.physics.vel[0] / 5.0,
            self.physics.vel[1] / 5.0,
            self.physics.angle / np.pi,
            self.physics.angular_vel / 2.0
        ], dtype=np.float32)


    def get_reward(self, action, crashed, landed):
        pos_x, pos_y = self.physics.pos
        vel_x, vel_y = self.physics.vel
        angle = self.physics.angle
        target_x, target_y = self.physics.landing_pad

        dist = np.sqrt((pos_x - target_x)**2 + (pos_y - target_y)**2)
        vel = np.sqrt(vel_x**2 + vel_y**2)

        # shaping reward
        shaping = - (dist * 100.0) - (vel * 100.0) - (abs(angle) * 100.0)
        reward = 0.0
        if self.prev_shaping is not None:
            reward = shaping - self.prev_shaping
        self.prev_shaping = shaping

        # punish using fuel (makes mor realistic suicide burn)
        if action in [1, 4, 5]:
            reward -= 1.0

        # punish high velocity near the ground
        if pos_y < 2.5 and vel_y < -0.8:
            reward -= 10.0 * abs(vel_y)

        # reward successfull landing and closeness to target
        if landed:
            landing_error = abs(pos_x - target_x)
            accuracy_bonus = max(0.0, 1000.0 - (500.0 * landing_error ** 2))
            reward += accuracy_bonus

        # punish crashing (had to reduce as rocket learned to hover and timeout)
        elif crashed:
            reward -= 100.0

        return reward

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        # calculation to make the rocket spawn higher and with more spread as it learns (equation generated by gemini coded by me)
        progress = min(1.0, self.episode_count / 3000.0)
        
        min_y = 1.5
        max_y = 2.0 + progress * 10.0
        start_y = np.random.uniform(min_y, max_y)
        
        pad_x = self.physics.landing_pad[0]
        x_spread = 0.5 + progress * 3.5
        start_x = np.random.uniform(pad_x - x_spread, pad_x + x_spread)
        
        self.physics.reset(pos=(start_x, start_y))
        self.steps = 0
        self.episode_count += 1

        # Calculation for shaping reward baseline
        target_x, target_y = self.physics.landing_pad
        dist = np.sqrt((start_x - target_x)**2 + (start_y - target_y)**2)
        vel = np.sqrt(self.physics.vel[0]**2 + self.physics.vel[1]**2)
        
        self.prev_shaping = - (dist * 100.0) - (vel * 100.0) - (abs(self.physics.angle) * 100.0)

        return self.get_observation(), {}


    def step(self, action):
        self.steps += 1
        crashed, landed = self.physics.step(action)

        # if it tilts too far we say its a crash
        if abs(self.physics.angle) > 1.5:       
            crashed = True
            landed = False

        observation = self.get_observation()
        reward = self.get_reward(action, crashed, landed)

        terminated = crashed or landed

        #timeout
        truncated = self.steps >= 600

        return observation, reward, terminated, truncated, {}

    def render(self):
        if self.renderer:
            self.renderer.render(self.physics.pos, self.physics.angle)

    def close(self):
        if self.renderer is not None:
            self.renderer.close()